### ISSUE TITLE
Cross-compiling a Python script on Linux into a Windows executable

### ISSUE THREAD

**Issue by tpd99** [tpd99/tpd99.github.io#10]
# https://stackoverflow.com/questions/2950971/cross-compiling-a-python-script-on-linux-into-a-windows-executable

**Comment by piratedv** [comment]
As mentioned by other answerers, the cross-compilation feature is removed from PyInstaller since 1.5. Here, show how to package a Windows executable from Python scripts using PyInstaller under wine.

Step 1: Install wine and Python

```
sudo apt-get install wine
wine msiexec /i python-2.7.10.msi /L*v log.txt
```

PS: Newer Python versions already include pip (is used to install pyinstaller). Download Python installation package from here (e.g., python-2.7.10.msi)

Step 2: Install PyInstaller on wine

```
$ cd ~/.wine/drive_c/Python27
$ wine python.exe Scripts/pip.exe install pyinstaller
Successfully installed pyinstaller-3.1.1 pypiwin32-219
```

Step 3: Package Python scripts

Package Python scripts (e.g., HelloWorld.py) with pyinstaller.

```
$ wine ~/.wine/drive_c/Python27/Scripts/pyinstaller.exe --onefile HelloWorld.py
```
```python
# filename: HelloWorld.py

#!/usr/bin/env python
# -*- coding: utf-8 -*-
print('Hello World!')

```
The Windows executable file is located in `dist/`.

```
$ wine dist/HelloWorld.exe 
Hello World!
fixme:msvcrt:__clean_type_info_names_internal (0x1e24e5b8) stub
```

Credits: [sparkandshine](https://stackoverflow.com/users/3067748/sparkandshine)
