### ISSUE TITLE
Learning Everything From Start To Finish

### ISSUE THREAD

**Issue by tpd99** [tpd99/tpd99.github.io#2]
This time I'll try to learn everything the "right" way or by following a guide.

I found [this](https://github.com/kamranahmedse/developer-roadmap) repository that might me get started learning everything from scratch again.

I will start following the front end development road map then move to back end. I will try to understand and find more guides for each topic/obstacle that I will be facing.

I don't know how I can fit this in my schedule but I'll make this work out.

**Comment by piratedv** [comment]
This is what I'll be learning in the next few weeks.

- HTML
- CSS
- Vanilla / ES6 Javascript

I will try to create at-least 1-3 projects for each topic. I think I should create a repository named "frontend roadmap" and dump all of the projects there. It'll be helpful to showcase them too. I'll be focusing more on **CSS** and **Javascript** since they are more important but I'll try to find an in-depth guide or explanation for **HTML** to compensate.

I still need to find a way fit this in my schedule.

![front end road map](https://github.com/kamranahmedse/developer-roadmap/raw/master/images/frontend.png)
